#!/bin/bash

# load aliases from bash profile
shopt -s expand_aliases
source ~/.bash_profile

# compile lexer file
antlr4 SlothLexer.g4 || exit 1

# compile parser file
antlr4 -no-listener SlothParser.g4 || exit 1

# compile generated java files
/usr/bin/javac *.java || exit 1

echo "All done!"
echo "To test grammar:"
echo     "grun Sloth program -tree < test.sl"
echo     "grun Sloth program -ps tree.ps < test.sl"


